disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - shorthand_operator
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - TasteMaker/ExternalLibraries/ALImageGallery.swift
  - TasteMaker/ExternalLibraries/WSTagsField/WSTagsField.swift
line_length: 500
type_body_length:
  - 600 # warning
  - 700 # error
function_body_length:
  - 200 # warning
  - 300 # error
function_parameter_count:
  - 8 # warning
  - 9 # error
cyclomatic_complexity:
  - 40 # warning
  - 50 # error
variable_name:
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 1
file_length:
  warning: 1000
  error: 1600
